create table
  public.grandezas (
    id bigint generated by default as identity not null,
    nome character varying not null,
    unidade character varying not null,
    constraint grandezas_pkey primary key (id),

    constraint nome_length check (char_length(nome) >= 3 AND char_length(nome) <= 255 ),
    constraint unidade_length check (char_length(unidade) >= 1 AND char_length(unidade) <= 5 )
  ) tablespace pg_default;