create table
  public.medidores (
    id bigint generated by default as identity not null,
    nome character varying not null,
    descricao character varying null,
    created_at timestamp with time zone null default now(),
    constraint medidores_pkey primary key (id),

    constraint nome_length check (char_length(nome) >= 3 AND char_length(nome) <= 255 ),
    constraint descricao_length check (char_length(descricao) >= 3 AND char_length(descricao) <= 255 )
  ) tablespace pg_default;