create table "public"."medidores" (
    "id" bigint generated by default as identity not null,
    "nome" varchar(255) not null,
    "descricao" varchar(255) not null,

    CHECK (char_length(nome) >= 3 AND char_length(nome) <= 255),
    CHECK (char_length(descricao) >= 3 AND char_length(descricao) <= 255)
);
CREATE UNIQUE INDEX medidores_pkey ON public.medidores USING btree (id);
alter table "public"."medidores" add constraint "medidores_pkey" PRIMARY KEY using index "medidores_pkey";

alter table "public"."medidores" enable row level security;
CREATE POLICY "Todos podem atualizar medidores" ON public.medidores FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Todos podem visualizar medidores" ON public.medidores FOR SELECT TO authenticated USING (true);
CREATE POLICY "Todos podem inserir medidores" ON public.medidores FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Ninguém pode apagar medidores" ON public.medidores FOR DELETE TO authenticated USING (false);
